version: '2'

# AFI Terraform Merge Pipeline
tasks:
  simple-execute:
    displayName: Toolchains Provision
    steps:
      - name: setup
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        onError: stopAndFail
        script: |
          #!/usr/bin/env bash
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/one_off/afi_terraform_merge
          chmod +x ${PATH_TO_PIPELINE}/steps/setup.sh
          ${PATH_TO_PIPELINE}/steps/setup.sh

      - name: unit-test
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        onError: stopAndFail
        script: |
          #!/usr/bin/env bash
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/one_off/afi_terraform_merge
          chmod +x ${PATH_TO_PIPELINE}/steps/test.sh
          ${PATH_TO_PIPELINE}/steps/test.sh

      - name: build-artifact
        when: 'false'

  devmode-code-build:
    displayName: Toolchains Provision
    steps:
      - name: setup
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        onError: stopAndFail
        script: |
          #!/usr/bin/env bash
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/one_off/afi_terraform_merge
          chmod +x ${PATH_TO_PIPELINE}/steps/setup.sh
          ${PATH_TO_PIPELINE}/steps/setup.sh

      - name: unit-test
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        onError: stopAndFail
        script: |
          #!/usr/bin/env bash
          export PATH_TO_GENCTL_CI="${WORKSPACE}/one-pipeline-config-repo"
          export PATH_TO_PIPELINE=${PATH_TO_GENCTL_CI}/onepipeline/pipelines/one_off/afi_terraform_merge
          chmod +x ${PATH_TO_PIPELINE}/steps/test.sh
          ${PATH_TO_PIPELINE}/steps/test.sh

      - name: build-artifact
        when: 'false'

  devmode-deploy-checks:
    when: 'false'

  devmode-deploy-release:
    when: 'false'

finally:
  code-ci-finish:
    steps:
      - name: run-stage
        image: us.icr.io/genctl-cicd-onepipeline/genctl/golang-ci:22.20260817071533
        script: |
          #!/usr/bin/env bash
          echo "AFI Terraform Merge Pipeline Finished"
          exit 0
